### PR TITLE
fix: pay screen background blink

### LINKED ISSUE #1233: bug: we can still see blink image during send page
Screenshot 2024-01-16 at 11 56 00
Screenshot 2024-01-16 at 11 56 05

this PR has not been resolving the issue:

https://github.com/espresso-cash/espresso-cash-public/pull/1145

### PR DESCRIPTION
**Pull request by justinenerio**
## Changes

pay screen background blink

## Related issues

Fixes #1233

## Video

<details>

https://github.com/espresso-cash/espresso-cash-public/assets/28533130/9199f59c-17cb-408b-9698-77cedffc1c9c

</details>

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

### CODE REVIEW

**Comment by antoineherzog** [comment]
@justinenerio can you show a video?

**Comment by justinenerio** [comment]
@antoineherzog added video

**Comment by antoineherzog** [comment]
is it normal ?
picture on top doesn't display right away
Screenshot 2024-02-05 at 12 44 50

**Comment by antoineherzog** [comment]
@justinenerio

**Comment by justinenerio** [comment]
@antoineherzog rerecorded the video, the previous was on debug mode which has slower performance

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
